In [ ]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

(891, 15)

In [100]:
(df["age"] < 18).sum()

np.int64(113)

Il y a 113 passagers de moins de 18 ans.

In [101]:
df.sort_values(by="fare", ascending=False).head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False

In [102]:
df.sort_values(by="fare", ascending=False)[["class", "embark_town", "fare"]].head(5)

     class  embark_town      fare
679  First    Cherbourg  512.3292
258  First    Cherbourg  512.3292
737  First    Cherbourg  512.3292
88   First  Southampton  263.0000
438  First  Southampton  263.0000

Voici les 5 billets les plus chers avec la classe ainsi que le port d'embarquement.

In [106]:
df[(df["sex"] == "female") & (df["class"] == "First")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [104]:
femme_1ere_classe = (df[(df["sex"] == "female") & (df["class"] == "First")].shape[0])
passagers_1ere_classe = (df[df["class"] == "First"].shape[0])
pourcentage_femmes_1ere_classe = (femme_1ere_classe / passagers_1ere_classe) * 100

print(f"Pourcentage de femmes dans la première classe : {pourcentage_femmes_1ere_classe:.2f}%")

Pourcentage de femmes dans la première classe : 43.52%

In [ ]:
df[(df["class"] == "First") & (df["sex"] == "female") & (df["alive"] == "yes")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [112]:
femmes_1ere_classe_vivantes = (df[(df["class"] == "First") & (df["sex"] == "female") & (df["alive"] == "yes")].shape[0])

print(f"Nombre de femmes vivantes 1ère classe : {femmes_1ere_classe_vivantes}")
print(f"Nombre de femmes au total 1ère classe : {femme_1ere_classe}")
print(f"Pourcentage de femmes vivantes 1ère classe uniquement : {(femmes_1ere_classe_vivantes / femme_1ere_classe) * 100:.2f}%")
print(f"Pourcentage de femmes vivantes 1ère classe sur l'ensemble des passagers : {(femmes_1ere_classe_vivantes / df.shape[0]) * 100:.2f}%")

Nombre de femmes vivantes 1ère classe : 91
Nombre de femmes au total 1ère classe : 94
Pourcentage de femmes vivantes 1ère classe uniquement : 96.81%
Pourcentage de femmes vivantes 1ère classe sur l'ensemble des passagers : 10.21%

In [115]:
hommes_3eme_classe = (df[(df["class"] == "Third") & (df["sex"] == "male")].shape[0])
hommes_3eme_classe_vivants = (df[(df["class"] == "Third") & (df["sex"] == "male") & (df["alive"] == "yes")].shape[0])

print(f"Nombre d'hommes vivants 3ème classe : {hommes_3eme_classe_vivants}")
print(f"Nombre d'hommes au total 3ème classe : {hommes_3eme_classe}")
print(f"Pourcentage d'hommes vivants 3ème classe uniquement : {(hommes_3eme_classe_vivants / hommes_3eme_classe) * 100:.2f}%") 
print(f"Pourcentage d'hommes vivants 3ème classe sur l'ensemble des passagers : {(hommes_3eme_classe_vivants / df.shape[0]) * 100:.2f}%")

Nombre d'hommes vivants 3ème classe : 47
Nombre d'hommes au total 3ème classe : 347
Pourcentage d'hommes vivants 3ème classe uniquement : 13.54%
Pourcentage d'hommes vivants 3ème classe sur l'ensemble des passagers : 5.27%